apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: llpfs-live-kisoong-leo-pipeline-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: kisoong-leo-react-next-pipeline
  workspaces:
    - name: pipeline-shared-data
      # persistentVolumeClaim:
      #   claimName: leo-liu-live-pvc-2nd
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi